apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: from-beginning-mongo-source-connector
  namespace: kafka-poc-ns
  labels:
    strimzi.io/cluster: kafka-connect-poc-cluster
spec:
  class: "com.mongodb.kafka.connect.MongoSourceConnector"
  tasksMax: 1
  config:
    #connection.uri: "mongodb://${file:/opt/kafka/external-configuration/mongo-credentials/mongo-credentials.properties:username}:${file:/opt/kafka/external-configuration/mongo-credentials/mongo-credentials.properties:password}@database.mongodb:27017"
    connection.uri: "mongodb://admin:password@mongodb-standalone-0:27017,admin:password@mongodb-standalone-1:27017"
    database: "admin"
    collection: "fruits"
    copy.existing: true
    topic.namespace.map: "{\"*\": \"from_beginning\"}"
    change.data.capture.handler: "com.mongodb.kafka.connect.sink.cdc.mongodb.ChangeStreamHandler"
# by default when string converter is not used then document is escaped by \ in kafka.
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "org.apache.kafka.connect.storage.StringConverter"
# test this tomorrow change.stream.full.document