apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-kafka-connect
  region: us-east-1

nodeGroups:
  - name: eks-kafka-ng-01
    instanceType: t2.medium
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      publicKeyPath: ~/keys/id_rsa.pub

  - name: eks-kafka-ng-02
    instanceType: t2.small
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      publicKeyPath: ~/keys/id_rsa.pub